chore: vercel deployment

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,10 +9,41 @@ permissions:
   contents: write
 
 jobs:
+  determine_tag:
+    runs-on: ubuntu-latest
+    outputs:
+      npm_tag: ${{ steps.determine_npm_tag.outputs.npm_tag }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Determine npm tag
+        id: determine_npm_tag
+        shell: bash
+        run: |
+          TAG="${GITHUB_REF#refs/tags/}"
+          if [[ "$TAG" =~ -(next|canary|beta|rc) ]]; then
+            # Extract pre-release tag (e.g., beta, rc)
+            NPM_TAG=${BASH_REMATCH[1]}
+          else
+            # Check if the commit is on the main branch
+            git fetch origin main
+            if git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
+              NPM_TAG="latest"
+            else
+              echo "The tagged commit is not on the main branch."
+              echo "::error ::Releases with the 'latest' npm tag must be on the main branch."
+              exit 1
+            fi
+          fi
+          echo "npm_tag=$NPM_TAG" >> $GITHUB_OUTPUT
+          echo "Using npm tag: $NPM_TAG"
+
   build:
     runs-on: ubuntu-latest
+    needs: determine_tag
     env:
-      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
+      TURBO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       TURBO_TEAM: ${{ vars.TURBO_TEAM }} 
     strategy:
       fail-fast: true
@@ -42,7 +73,7 @@ jobs:
 
   publish:
     runs-on: ubuntu-latest
-    needs: build
+    needs: [determine_tag, build]
     strategy:
       fail-fast: false
       matrix:
@@ -60,31 +91,28 @@ jobs:
           name: build-${{matrix.package}}
           path: ${{ matrix.package == 'cli' && 'packages/cli/build' || format('apps/{0}/build', matrix.package) }}
 
-      - name: Determine npm tag
-        id: determine_npm_tag
-        shell: bash
-        run: |
-          TAG="${GITHUB_REF#refs/tags/}"
-          if [[ "$TAG" =~ -(next|canary|beta|rc) ]]; then
-            # Extract pre-release tag (e.g., beta, rc)
-            NPM_TAG=${BASH_REMATCH[1]}
-          else
-            # Check if the commit is on the main branch
-            git fetch origin main
-            if git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
-              NPM_TAG="latest"
-            else
-              echo "The tagged commit is not on the main branch."
-              echo "::error ::Releases with the 'latest' npm tag must be on the main branch."
-              exit 1
-            fi
-          fi
-          echo "npm_tag=$NPM_TAG" >> $GITHUB_OUTPUT
-          echo "Using npm tag: $NPM_TAG"
-
       - name: Publish ${{matrix.package}} to npm
         run: |
           cd ${{ matrix.package == 'cli' && 'packages/cli/build' || format('apps/{0}/build', matrix.package) }}
-          bun publish --verbose --access public --tag ${{ steps.determine_npm_tag.outputs.npm_tag }}
+          bun publish --verbose --access public --tag ${{ needs.determine_tag.outputs.npm_tag }}
         env:
           NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+  vercel_deploy:
+    runs-on: ubuntu-latest
+    needs: [determine_tag, publish]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Vercel CLI
+        run: bun add --global vercel@latest
+
+      - name: Deploy app to Vercel
+        run: vercel deploy ${{ needs.determine_tag.outputs.npm_tag == 'latest' && '--prod' || '' }}
+        env:
+          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
+          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+
+         
